#Each term in the fibonacci sequence is generated by adding the previous two numbers. By starting with 1 and 2, the first #ten fibonacci terms will be 1,2,3,5,8,13,21,34,55,89.
#By considering the terms in the fibonacci sequence, whose value do not exceed 4 million, the sum of the even terms..

l=[]
i=1
sum=0
while i<=100:
    if i==1 or i==2:
        l.append(i)
        i=i+1
    else:
        fib = l[i-2]+l[i-3]
        l.append(fib)
        i=i+1
        
for j in l:
    if j<4000000:
        if j%2==0:
            sum = sum + j
    else:
        break

print(sum)





